### ISSUE TITLE
fasd process always in background

### ISSUE THREAD

**Issue by derekstavis** [oh-my-fish/plugin-fasd#6]
When this plugin is installed it hooks to `fish_preexec` and keeps backgrounding a `fasd` process.

I found that this is the offending line:
https://github.com/oh-my-fish/plugin-fasd/blob/master/init.fish#L5

Removing the backgrounding ampensand (`&`) should fix the issue.

**Comment by simnalamburt** [comment]
Actually this part is can be very controversial, since that `&` is added intensionally (0f5fa7c60f).

The original intent of `&` is to make plugin-fasd faster. Without it, we need to run `fasd --proc $argv` everytime we push enter _synchronously_ which is not necessary.

But at the same time, this unending background job can be very annoying for some users who uses shell theme which warns the background job.

So here's my suggestion. Let's make an option variable like `FASD_SYNC`, `FASD_FOREGROUND` or whatever. And let `init.fish` detect it so make `&` optional. What do you thing?

**Comment by derekstavis** [comment]
Hmm, I see it was intentional. No problem. But what does this background command? Does it really need to run on `fish_preexec`? I'm just asking to better understand `fasd` integration.

**Comment by simnalamburt** [comment]
We do need to execute `fasd --proc` everytime we manipulate fish but its location does not need to be in `fish_preexec`. As you can see, many other shells which do not have `~_preexec` run this command in `$PS1`

**Comment by derekstavis** [comment]
I have another idea. You can put the event on PWD variable change using `--on-variable PWD`.

**Comment by simnalamburt** [comment]
Good idea but I don't have enough knowledge about fish to decide this. Does putting `fasd --proc` in `--on-variable PWD` instead of `fish_preexec` gives us any serious performance gain?

By the way official fasd performs `fasd --proc` in `zsh_preexec`.

**Comment by therealpxc** [comment]
For some reason the whole theme alerting me to background process thing just started happening to me recently (idk if it was changes to the theme or because I'm using newer fish so the theme detected new capabilities), and I found it super freaking annoying, so I decided to just [try](https://github.com/therealpxc/plugin-fasd) Derek's suggestion and see how it works.

So far it's not bad. I think I'll make a PR if I still feel good about it in a few weeks. Does that sound reasonable?

**Comment by simnalamburt** [comment]
@therealpxc Yes! I'm with you, please send us a PR!

**Comment by Jomik** [comment]
I tried the solution that @therealpxc came up with. This makes it so that fasd doesn't detect files, it seems.
The background process is annoying though. As I can't exit the shell without having to write exit twice to force it... :-1:

**Comment by therealpxc** [comment]
Hm... I generally don't use fasd to access files, so I didn't notice. I've been happy with the way this works.

How is file detection supposed to work and what is the undesired behavior you're observing, @Jomik ?

**Comment by Jomik** [comment]
Well, file access is really the only reason I'd chose fasd over z.
It lets you do stuff like `mv (f somefile) ./`, by running the commands in subshells, they only return the best match. I believe that the preexec hooks lets fasd see what files you're accessing form your cli, and then it adds those to the database. This doesn't happen if you only observe $PWD changes, from what I saw @therealpxc.

Examples from the fasd git.
```
mv update.html (d www)
cp (f mov) .
```

**Comment by therealpxc** [comment]
Hey, friends! The [new `fish` release](https://fishshell.com/release_notes.html) (`2.6.0`) resolves the [underlying issue](https://github.com/fish-shell/fish-shell/issues/2810) with background processes so there should be a way to manage this which leaves the process in the background but `disown`s it so we don't have to fuss with forcing an `exit` by typing the command twice.

I don't have time to play with this plugin right now but I think it's an easy fix. @Jomik might be especially glad to know. :-)
